# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0be95f187a184330636c50eaca0daa98ce9d8b51d84cd14a7bbab8d0c68df0bf137c186978afc879ed27059ef2642f17b15c770df76a4a5568b1f49e92bb7b56

test:
  secret_key_base: 7cb6538a28c2c6b6c370f63efccb21b413646e28e8865cc518ffbd45810bb4bfe6cb757ea5593be537a3011f928598723f3b740a58853a597b45c31a65f7128c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
